### ISSUE TITLE
EntryPointNotFoundException thrown when using arrays

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Usable#10]
The following code

```c#
    public void ArrayTest()
    {
        var strs = new Stream[] {};
        // code
    }
```

produces

```c#
    public void ArrayTest()
    {
        using (new Stream[0])
        {
            // code
        }
    }
```

which throws the EntryPointNotFoundException when it tries to exit the using block.

It doesn't really make sense to wrap an array with a using block, as this is not even valid c#.

I see two possible solutions:

1. Skip weaving when dealing with an array.
2. Produce code similar to the following

```c#
    public void ArrayTest()
    {
        var array = new Stream[0];
        try
        {
            // code
        }
        finally
        {
            foreach (var obj in array)
            {
                obj.Dispose();
            }
        }
    }
```

Thoughts?

**Comment by distantcam** [comment]
I like option 1. Want to send a pr?
