### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Usable#16]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by Janek91** [comment]
There is no NuGet dependency to Fody.Cecil in current Fody.Usable version - what causes compilation error and need to install it separately.

**Comment by SimonCropp** [comment]
@Janek91 feel like submitting a pull request?
