### ISSUE TITLE
MSBuild error: No weavers found for the configuration entries Usable

### ISSUE THREAD

**Issue by mzhukovs** [Fody/Usable#32]
#### Describe the issue

Is <Usable/> required to be in the FodyWeaver.xml file? Because when I include it, I get the following error:

**MSBUILD : error : Fody: No weavers found for the configuration entries Usable. Add the desired weavers via their nuget package.** 

Here are the project/IDE details:

- VS2019 Enterprise latest version
- NETStandard.Library v2.0.3
- Fody v4.2.1
- Usable.Fody v0.3.5

FodyWeavers.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <AsyncErrorHandler />
  <MethodTimer />
  <PropertyChanged />
  <Usable />
</Weavers>
```

My .csproj package references:
 ```
 <ItemGroup>
    <PackageReference Include="AsyncErrorHandler.Fody" Version="1.2.3" />
    <PackageReference Include="Fody" Version="4.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MethodTimer.Fody" Version="2.3.3" />
    <PackageReference Include="PropertyChanged.Fody" Version="2.6.1" />
    <PackageReference Include="Usable.Fody" Version="0.3.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

#### Minimal Repro

1. Create a new .NET Standard Class library
2. Add the packages as listed above
3. Update the Weaver file to include <Usable />
4. Build, see error

#### Submit a PR that fixes the bug

I don't know how?  :(

**Comment by ltrzesniewski** [comment]
This project is archived and no longer being maintained. That's why it's no longer compatible with newer versions of Fody (there have been 4 major versions of Fody released since the last version of Usable.Fody - it's *really* outdated).
You *may* try to use a very old version of Fody along with all its addins, buty it's not a very good idea and it's very possible it will fail for various reasons. Your best bet would be to stop using Usable.Fody or to request ownership of the package and fix it yourself.

**Comment by mzhukovs** [comment]
@ltrzesniewski I see, thanks for the response.

**Comment by SimonCropp** [comment]
@mzhukovs as @ltrzesniewski mentioned, ownership of this project can be transferred to you if you want to reboot it

**Comment by SimonCropp** [comment]
closing this one for now. please let me know if you want to take ownership
