### ISSUE TITLE
Issue with nested streams

### ISSUE THREAD

**Issue by StefanOssendorf** [Fody/Usable#9]
When using nested Streams usable is "killing" the application. I get an exception *InvalidProgramException* with *Common Language Runtime detected an invalid program*.

My test solution contains 2 projects (full framework 4.5.2):
- Console application
- Library

Content of console application:
```c#
 class Program {
        static void Main(string[] args) {
            var c1 = new MyClass();
            Console.WriteLine(c1.Name);
            var str = c1.DoDummy();
            str.AutoFlush = true;
            str.WriteLine("krznbf");
        }
    }
```

Content of library:
```c#
public class MyClass {
        public string Name { get; set; }

        public StreamWriter DoDummy() {
            var s0 = new FileStream("krznbf.txt", FileMode.Append);
            Name = "krznbf;"; // Important! Otherwise the compiler optimize this code.
            return new StreamWriter(s0);
        }
    }
```

Now you can't run the program, because the library is rewritten to (dotPeek used):
```c#
using System.IO;

namespace Kzrnbf2Assembly
{
  public class MyClass
  {
    public string Name { get; set; }

    public StreamWriter DoDummy()
    {
      using (FileStream fileStream = new FileStream("krznbf.txt", FileMode.Append))
      {
        this.Name = "krznbf;";
        return new StreamWriter((Stream) fileStream);
      }
    }
  }
}
```

The `FileStream` disposing is causing this issue.

**Comment by StefanOssendorf** [comment]
bump

**Comment by SimonCropp** [comment]
@StefanOssendorf how about a PR?

**Comment by distantcam** [comment]
That's exactly what Usable is supposed to do. The `filestream` variable is locally scoped and so it is wrapped in a using.

You could try returning the filestream itself, instead of wrapping it in the StreamWriter.

**Comment by SimonCropp** [comment]
seems this is working as designed. so closing
